theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
rulers = [80, 120]
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
